language: cpp
compiler: gcc
before_install:
# As of this writing (10 May 2014) the Travis build environment is Ubuntu 12.04,
# which needs the following ugly dependency incantations to build RocksDB:
# Get GCC 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq gcc-4.8 g++-4.8 zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
# Get Deps:
# cmake
  - sudo apt-get install -y cmake
# mysql++
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y libmysqlclient-dev libmysql++-dev libmysqlcppconn-dev
# boost 1.54:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost1.54-all-dev
# libev
  - sudo apt-get install -y libev-dev
# gmock / gtest
  - sudo apt-get install -y unzip
  - curl -o ../gmock-1.7.0.zip -O https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  - unzip ../gmock-1.7.0.zip -d ..
  - cd ../gmock-1.7.0
  - cmake .
  - make
  - cd ../ocelot # Return to project directory for tests

before_script:
# Setup test DB dump
  - mysql -e 'create database gazelle;' -u root
  - mysql -u root gazelle < test/snapshot.sql

script:
  - cp src/config.cpp.template src/config.cpp
  - cmake . -DBUILD_TESTING=ON
  - make ocelot_tests
  - ./bin/ocelot_tests
notifications:
  email: false